theme: jekyll-theme-slate
title: "IT Lab 2018"
description: "These are the notes and exercises for the ITLAB 2018, for SCIS, UoH."
includes: scripts.html
---
 - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
---